services:
  ffc-sfd-permissions:
    build:
      context: .
      target: production
    image: ffc-sfd-permissions
    container_name: ffc-sfd-permissions
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-sfd-permissions-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      AUTH_HOST: ${AUTH_HOST:-http://ffc-ffd-proxy:3000}
      GATEWAY_HOST: ${GATEWAY_HOST:-http://localhost:3000}
      DATA_HOST: ${DATA_HOST:-http://ffc-ffd-data:3004/graphql}
