# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ffc-sfd-permissions:
    build:
      target: development
    image: ffc-sfd-permissions-development
    container_name: ffc-sfd-permissions-development
    ports:
      - "3005:3005"
      - "9005:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
